name: GoldenHeadDetector3000
main: com.gmail.prizmahdiep.GoldenHeadDetector3000
version: 99.0
api-version: '1.20'
description: Quita la jodida saturación
author: EL BOCHES
depends: ["ConsumeFood"]
    